language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_script:
  - export PATH=$PATH:~/.cargo/bin
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        export FEATURES="--all-features";
    else
        export FEATURES="";
    fi
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        ( cargo install clippy && export CLIPPY=true ) || export CLIPPY=false;
    else
        export CLIPPY=false;
    fi

script:
  - bash ./ci/script.sh

after_success:
  - bash ./ci/after_success.sh
